Models/Candidate.cs
using System;
using System.ComponentModel.DataAnnotations;


namespace Proje.Models
{
    public class Candidate
    {

        [Required(ErrorMessage = "E-mail is required.")] // doldurmak zorunlu uyarrısı
        public String? Email { get; set; } = String.Empty;

        [Required(ErrorMessage = "FirstName is required.")] // doldurmak zorunlu uyarrısı
        public String? FirstName { get; set; } = String.Empty;

        [Required(ErrorMessage = "LastName is required.")]  // doldurmak zorunlu uyarrısı
        public String? LastName { get; set; } = String.Empty;
        public String? FullName => $"{FirstName} {LastName?.ToUpper()}"; // read only ifade

        [Required(ErrorMessage = "Birthday is required.")]  // doldurmak zorunlu uyarrısı
        public DateOnly Birthday { get; set; }

        [Required(ErrorMessage = "Password is required.")]
        public string Password { get; set; } = string.Empty;


        public DateTime ApplyAt { get; set; }
        public Candidate()
        {
            ApplyAt = DateTime.Now;
        }
    }
}

Models/ErrorViewModel.cs
namespace Proje.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Repository.cs
using System;
using System.Collections.Generic;


namespace Proje.Models // MODEL kullanmak için 

{
    public static class Repository // uygulamayı kullanan herkes bellek üzerinde statik
    // olarak tanımlanmış bir alandan faydalanacak.
    {
        private static List<Candidate> applicaitons = new(); 

        public static IEnumerable<Candidate> Applications => applicaitons; // "readonly" bir özellik
        // sınıf dışından erişmek için arayüz desteğiyle kullanılması için oluşturulan özellik

        public static void Add(Candidate candidate)//formdan gelen elemanları ekler.
        {
            applicaitons.Add(candidate);
        }


    }
}

Controllers/ClinicController.cs
using Microsoft.AspNetCore.Mvc;
using Proje.Models;

namespace Proje.Controllers
{
    public class ClinicController : Controller
    {
        public IActionResult Index()
        {
            var candidates = Repository.Applications.ToList(); // List<Candidate> türünde veri döndürür
            return View("Apply/Apply", candidates); // View'e List<Candidate> gönder
        }


        public IActionResult Apply()
        {
            var model = new Candidate(); // Boş bir model oluştur
            return View("Apply/Apply", model); // Modeli View'e gönder
        }


        // public IActionResult Apply() // GET için çalışan method. Eğer başına [Http POST]
        //                              // koymazsak tüm actionlar get ile çalışır.
        // {
        //     var model = Repository.Applications;
        //     return View(model);

        // }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Apply([FromForm] Candidate model) // POST için çalışan method.
                                                               // sunucuya aktaralıcak bu model,  form üzerindeki verilerle doldurulmuştur.buna model binding denir. 
                                                               // bu kısma [] ekleyerek belli bir yerden gelmesini istediğimizi belirtebiliriz. örn:[FromForm]                   
        {
            if (Repository.Applications.Any(c => c.Email.Equals(model.Email))) // parametre ifadeyle email ifadesini karşılaştırıp aynı emaille 
            // birden fazla kayıtı engeller.
            {
                ModelState.AddModelError("", "There is already application for you");
            }
            if (ModelState.IsValid) // modelde değer olduğunda if bloğunu çalıştırır.
            {
                Repository.Add(model);//apply tıklandığında redirect mekanizmasını çalıştırıp
                                      //kök ("/")yani home gitmesini sağlar.
                return View("Feedback", model);
            }
            return View(); // eğer başarısız ise aynı sayfaya dön 
        }

        public IActionResult Login()
        {
            return View("Login/Login");
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Proje.Models;

namespace BtkAkademi.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

 

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;

namespace Proje.Controllers
{
    public class ProfileController : Controller
    {
        public IActionResult Profile()
        {
            return View();
        }
    }
}

Views/Clinic/Apply/Apply.cshtml
@model Proje.Models.Candidate

<div class="display-6">
    Apply
</div>
<!-- post ile sunucu tarafında kaynak oluşturma-->
<form method="post" asp-action="Apply/Apply"> <!-- taghelpers: href yerine asp-action ya da 
    asp-controller vb. kullanılması -->
    <div class="text-danger" asp-validation-summary="All"></div> <!-- tüm doğrulama özetini sunmak -->

    <div class="form-group my-2">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" />
    </div>

    <div class="form-group my-2">
        <label asp-for="FirstName"></label>
        <input asp-for="FirstName" class="form-control" />
    </div>

    <div class="form-group my-2">
        <label asp-for="LastName"></label>
        <input asp-for="LastName" class="form-control" />
    </div>

    <div class="form-group my-2">
        <label asp-for="Birthday"></label>
        <input asp-for="Birthday" class="form-control" />
    </div>

    <div class="form-group my-2">
        <label asp-for="Password"></label>
        <input asp-for="Password" type="password" class="form-control" />
    </div>


    <div>
        <button class="btn btn-primary" type="submit">Apply</button>
        <a class="btn btn-warning" asp-controller="Home" asp-action="Index">Home</a>
    </div>
</form>

Views/Clinic/Apply/Feedback.cshtml
<!-- 
Bir action a bağlı olmayan bir feedback sayfası 
formun gönnderilmesi sonrası
-->

@model Candidate

<div>
    <h3 class="display-4">Congratulations @Model.FullName </h3>
    <p class="lead">Your application has been <mark>accepted.</mark></p>
    <p class="lead">Many thanks for your interest.</p>
    <hr />
  
    <p class="text-muted">You applied at @Model.ApplyAt.</p>

    <div class="btn-group">
        <a class="btn btn-outline-success" asp-action="Index">Applications</a>
        <a class="btn btn-success" asp-action="Index" asp-controller="Home">Home</a>
    </div>
</div>

Views/Clinic/Login/Login.cshtml
@model Proje.Models.Candidate

<div class="display-6">
    Login
</div>
<!-- post ile sunucu tarafında kaynak oluşturma-->
<form method="post" asp-action="Login">
    <!-- taghelpers: href yerine asp-action ya da
    asp-controller vb. kullanılması -->
    <div class="text-danger" asp-validation-summary="All"></div> <!-- tüm doğrulama özetini sunmak -->

    <div class="form-group my-2">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" />
    </div>

    <div class="form-group my-2">
        <label asp-for="Password"></label>
        <input asp-for="Password" class="form-control" />
    </div>


    <div>
        <button class="btn btn-primary" type="submit">Log in</button>
        <a class="btn btn-warning" asp-controller="Home" asp-action="Index">Home</a>
        <a class="btn btn-warning" asp-controller="Profile" asp-action="Index">Profile</a>
    </div>
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Ağız ve Diş Sağlığı Merkezi</h1>
    
    <div class="btn-group">
        <a class=" btn btn-primary" asp-controller="Clinic" asp-action="Apply">Kaydol</a>
        <a class="btn btn-outline-primary" asp-controller="Clinic" asp-action="Login">Oturum Aç</a>
    </div>
  
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BtkAkademi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BtkAkademi.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ağız ve Diş Sağlığ Merkezi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                     
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clinic" asp-action="Apply">Kaydol</a> <!--sayfanın sol üst köşedeki kısma apply butonunu linkini ekledik-->
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clinic" asp-action="Login">Oturum Aç</a> <!--sayfanın sol üst köşedeki kısma apply butonunu linkini ekledik-->
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Ağız ve Diş Sağlığı Merkezi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>